### PR TITLE
Use flask and makes it a WSGI application

### PR DESCRIPTION
**Pull request by marmeladema**
Tested on python 2.7.9 and 3.4.2

Minor modifications:
	* check for root effective uid before calling alsactl store, this way we can use a non privileged user, but then we cannot store alsa config
	* use argparse module to parse arguments
Ideas:
	* use jinja2 template engine (integrated with flask) for index / do not use templates at all for index ?

### CODE REVIEW

**Comment by marmeladema** [comment]
I forgot to change tests for flask. I'll to that in a few days. I lack of time right now.

**Comment by JiriSko** [comment]
Looks promising :) But needs a little work to do e.g. not working /card/ action (cannot change sound card right now).

**Comment by marmeladema** [comment]
I fixed some bugs, but in order to properly adapt tests i would have to import alsamixer-webui.py which is not possible because of the dash. Would you mind if i rename it to alsamixer_webui.py ?

**Comment by JiriSko** [comment]
Yes, I find out same issue a few days ago. At that time I decided to preserve name for backwards compatibility but now when there's different situation (new cli arguments) I think we can rename it.
Just for backwards compatibility please create temporary alsamixer-webui.py script which calls new alsamixer_webui.py. :-)

**Comment by marmeladema** [comment]
Tests are actualy good but alsa is missing on travis ...

**Comment by JiriSko** [comment]
Missing alsa is problem but if there would be alsa available you cannot test it properly without sound card(s). Thus I decided to test only webserver itself and ignore this OSError exception.

**Comment by marmeladema** [comment]
Is this ok for merge ?

**Comment by JiriSko** [comment]
I'll look at it in second half of this week. ;)

**Comment by JiriSko** [comment]
I've checked it. :)
I found several little issues - not working equalizer, can't change sound card and syntax error in init script. I fixed it.
Also I've decided to delete old alsamixer-webui.py because I realized that it won't work because of new dependency on the flask.
So good work, thanks! I'll merge it soon if there wouldn't be another issue. ;)

**Pull request merged**
